apiVersion: v1
kind: Service
metadata:
  name: {{ include "full-house.fullname" . }}
  labels: {{- include "full-house.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{ if .Values.service.clusterIP -}}
  clusterIP: {{.Values.service.clusterIP}}
  {{- end }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector: {{- include "full-house.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity | quote }}
  sessionAffinityConfig: {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
